width:
  value: 1600
  max_value: 1600
  min_value: 480
  
height:
  value: 900
  max_value: 900
  min_value: 320
  
framerate:
  value: 144
  max_value: 240
  min_value: 60
  
update_rate:
  value: 5000
  max_value: 5000
  min_value: 200
  
wall_aware:
  value: 150
  max_value: 150
  min_value: 50
  
dt:
  value: 0.005
  max_value: 10.0
  min_value: 0.000005

perch_division_rate:
  value: 5000
  max_value: 50000
  min_value: 500

pike_division_rate:
  value: 5000
  max_value: 5000
  min_value: 50

pike_starvation_rate:
  value: 250
  max_value: 5000
  min_value: 50
