width:
  value: 800
  max_value: 1280
  min_value: 480
  
height:
  value: 600
  max_value: 720
  min_value: 320
  
framerate:
  value: 144
  max_value: 240
  min_value: 60
  
update_rate:
  value: 500
  max_value: 2000
  min_value: 200
  
wall_aware:
  value: 50
  max_value: 150
  min_value: 50
  
dt:
  value: 0.005
  max_value: 10.0
  min_value: 0.000005
